parameters:

  cached_templates_dir: 'twig'

services:

  ##################################################
  # Twig
  ##################################################

  twig.environment:
    class: 'Twig_Environment'
    arguments:
      - '@twig.loader.file_system'
      - {debug: '%is_debug%', cache: '@=parameter("is_debug") ? false : parameter("root_dir") ~ "/" ~ parameter("cache_dir") ~ "/" ~ parameter("cached_templates_dir")', strict_variables: '%is_debug%'}

  twig.loader.file_system:
    class: 'Twig_Loader_Filesystem'
    arguments:
      - '%root_dir%/templates'
    calls:
      - ['addPath', ['%root_dir%/templates/layouts', 'layouts']]

  ##################################################
  # Twig Views
  ##################################################

  homepage_view:
    class: 'SolarCar\Homepage\View'
    arguments:
      - '@twig.environment'
